// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9_0sXPwh32i_s5-hREQRKeINF6oMQuu4',
    appId: '1:329648345045:web:e760b209708aec03f8775c',
    messagingSenderId: '329648345045',
    projectId: 'cineholmesfirst',
    authDomain: 'cineholmesfirst.firebaseapp.com',
    storageBucket: 'cineholmesfirst.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYKGK6gevYO-pydikl3gojpsiaETQzms',
    appId: '1:329648345045:android:945202a9ac9d0c2bf8775c',
    messagingSenderId: '329648345045',
    projectId: 'cineholmesfirst',
    storageBucket: 'cineholmesfirst.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhow9RN6J3NXc6nt3vMO2evDw8AtMG1RE',
    appId: '1:329648345045:ios:9088ebd4aacee18ef8775c',
    messagingSenderId: '329648345045',
    projectId: 'cineholmesfirst',
    storageBucket: 'cineholmesfirst.firebasestorage.app',
    iosBundleId: 'com.example.projectv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhow9RN6J3NXc6nt3vMO2evDw8AtMG1RE',
    appId: '1:329648345045:ios:9088ebd4aacee18ef8775c',
    messagingSenderId: '329648345045',
    projectId: 'cineholmesfirst',
    storageBucket: 'cineholmesfirst.firebasestorage.app',
    iosBundleId: 'com.example.projectv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9_0sXPwh32i_s5-hREQRKeINF6oMQuu4',
    appId: '1:329648345045:web:83f69ad2b6da018ef8775c',
    messagingSenderId: '329648345045',
    projectId: 'cineholmesfirst',
    authDomain: 'cineholmesfirst.firebaseapp.com',
    storageBucket: 'cineholmesfirst.firebasestorage.app',
  );

}